// 샘플 루틴 데이터 - ADHD 사용자를 위한 주간 루틴 예시
import type { RoutineData } from "../types";

export const sampleRoutineData: RoutineData = {
  routine_name: "ADHD 주간 루틴",
  version: "1.0.0",
  timezone: "Asia/Seoul",
  sleep: {
    target_bedtime: "23:00",
    target_wakeup: "07:00",
    flex_hours: 1,
  },
  days: [
    {
      day: "monday",
      label: "월요일",
      blocks: [
        {
          id: "mon-1",
          title: "모닝 루틴",
          category: "자기관리",
          start: "07:00",
          end: "07:40",
          duration_minutes: 40,
          priority: "urgent_not_important",
          color: "#F59E0B",
          required: true,
          notes: "세수, 양치, 스트레칭",
        },
        {
          id: "mon-2",
          title: "아침 식사",
          category: "식사",
          start: "07:40",
          end: "08:10",
          duration_minutes: 30,
          priority: "urgent_not_important",
          color: "#10B981",
          required: true,
        },
        {
          id: "mon-3",
          title: "딥워크 - 핵심 업무",
          category: "업무",
          start: "09:00",
          end: "11:00",
          duration_minutes: 120,
          priority: "urgent_important",
          color: "#3B82F6",
          required: true,
          notes: "가장 집중력 높은 시간대 활용",
        },
        {
          id: "mon-4",
          title: "짧은 산책 휴식",
          category: "휴식",
          start: "11:00",
          end: "11:20",
          duration_minutes: 20,
          priority: "not_urgent_not_important",
          color: "#8B5CF6",
          required: false,
        },
        {
          id: "mon-5",
          title: "이메일 및 행정 처리",
          category: "업무",
          start: "14:00",
          end: "15:00",
          duration_minutes: 60,
          priority: "urgent_not_important",
          color: "#3B82F6",
          required: false,
          notes: "낮은 집중력 필요 업무",
        },
      ],
    },
    {
      day: "tuesday",
      label: "화요일",
      blocks: [
        {
          id: "tue-1",
          title: "모닝 루틴",
          category: "자기관리",
          start: "07:00",
          end: "07:40",
          duration_minutes: 40,
          priority: "urgent_not_important",
          color: "#F59E0B",
          required: true,
        },
        {
          id: "tue-2",
          title: "운동 - 유산소",
          category: "운동",
          start: "08:00",
          end: "08:45",
          duration_minutes: 45,
          priority: "not_urgent_important",
          color: "#EF4444",
          required: true,
          notes: "조깅 또는 자전거 30분 + 쿨다운",
        },
        {
          id: "tue-3",
          title: "프로젝트 작업",
          category: "업무",
          start: "09:30",
          end: "11:30",
          duration_minutes: 120,
          priority: "urgent_important",
          color: "#3B82F6",
          required: true,
        },
        {
          id: "tue-4",
          title: "점심 식사 + 낮잠",
          category: "식사",
          start: "12:00",
          end: "13:00",
          duration_minutes: 60,
          priority: "urgent_not_important",
          color: "#10B981",
          required: true,
          notes: "20분 파워냅 포함",
        },
        {
          id: "tue-5",
          title: "독서 시간",
          category: "자기계발",
          start: "20:00",
          end: "20:45",
          duration_minutes: 45,
          priority: "not_urgent_not_important",
          color: "#6366F1",
          required: false,
        },
      ],
    },
    {
      day: "wednesday",
      label: "수요일",
      blocks: [
        {
          id: "wed-1",
          title: "모닝 루틴",
          category: "자기관리",
          start: "07:00",
          end: "07:40",
          duration_minutes: 40,
          priority: "urgent_not_important",
          color: "#F59E0B",
          required: true,
        },
        {
          id: "wed-2",
          title: "딥워크 - 창의적 작업",
          category: "업무",
          start: "09:00",
          end: "11:00",
          duration_minutes: 120,
          priority: "urgent_important",
          color: "#3B82F6",
          required: true,
          notes: "디자인, 기획, 글쓰기 등",
        },
        {
          id: "wed-3",
          title: "팀 미팅",
          category: "업무",
          start: "14:00",
          end: "15:00",
          duration_minutes: 60,
          priority: "urgent_not_important",
          color: "#0EA5E9",
          required: true,
        },
        {
          id: "wed-4",
          title: "명상 및 호흡",
          category: "자기관리",
          start: "17:00",
          end: "17:20",
          duration_minutes: 20,
          priority: "not_urgent_important",
          color: "#8B5CF6",
          required: false,
          notes: "마음챙김 명상 15분",
        },
      ],
    },
    {
      day: "thursday",
      label: "목요일",
      blocks: [
        {
          id: "thu-1",
          title: "모닝 루틴",
          category: "자기관리",
          start: "07:00",
          end: "07:40",
          duration_minutes: 40,
          priority: "urgent_not_important",
          color: "#F59E0B",
          required: true,
        },
        {
          id: "thu-2",
          title: "운동 - 근력",
          category: "운동",
          start: "08:00",
          end: "09:00",
          duration_minutes: 60,
          priority: "not_urgent_important",
          color: "#EF4444",
          required: true,
          notes: "상체/하체 분할 운동",
        },
        {
          id: "thu-3",
          title: "집중 업무 블록",
          category: "업무",
          start: "09:30",
          end: "11:30",
          duration_minutes: 120,
          priority: "urgent_important",
          color: "#3B82F6",
          required: true,
        },
        {
          id: "thu-4",
          title: "자유 시간",
          category: "휴식",
          start: "16:00",
          end: "17:00",
          duration_minutes: 60,
          priority: "not_urgent_not_important",
          color: "#8B5CF6",
          required: false,
          notes: "취미 활동 또는 산책",
        },
        {
          id: "thu-5",
          title: "주간 회고 준비",
          category: "자기계발",
          start: "21:00",
          end: "21:30",
          duration_minutes: 30,
          priority: "not_urgent_important",
          color: "#6366F1",
          required: false,
        },
      ],
    },
    {
      day: "friday",
      label: "금요일",
      blocks: [
        {
          id: "fri-1",
          title: "모닝 루틴",
          category: "자기관리",
          start: "07:00",
          end: "07:40",
          duration_minutes: 40,
          priority: "urgent_not_important",
          color: "#F59E0B",
          required: true,
        },
        {
          id: "fri-2",
          title: "주간 정리 업무",
          category: "업무",
          start: "09:00",
          end: "11:00",
          duration_minutes: 120,
          priority: "urgent_important",
          color: "#3B82F6",
          required: true,
          notes: "미완료 업무 정리, 다음 주 계획",
        },
        {
          id: "fri-3",
          title: "점심 외식",
          category: "식사",
          start: "12:00",
          end: "13:00",
          duration_minutes: 60,
          priority: "not_urgent_not_important",
          color: "#10B981",
          required: false,
        },
        {
          id: "fri-4",
          title: "주간 회고",
          category: "자기계발",
          start: "15:00",
          end: "15:45",
          duration_minutes: 45,
          priority: "not_urgent_important",
          color: "#6366F1",
          required: true,
          notes: "이번 주 성과 및 개선점 정리",
        },
      ],
    },
    {
      day: "saturday",
      label: "토요일",
      blocks: [
        {
          id: "sat-1",
          title: "늦잠 + 브런치",
          category: "식사",
          start: "09:00",
          end: "10:00",
          duration_minutes: 60,
          priority: "not_urgent_not_important",
          color: "#10B981",
          required: false,
          notes: "주말 여유 있는 아침",
        },
        {
          id: "sat-2",
          title: "운동 - 야외 활동",
          category: "운동",
          start: "10:30",
          end: "11:30",
          duration_minutes: 60,
          priority: "not_urgent_important",
          color: "#EF4444",
          required: false,
          notes: "등산, 수영, 자전거 중 택1",
        },
        {
          id: "sat-3",
          title: "취미 시간",
          category: "휴식",
          start: "14:00",
          end: "16:00",
          duration_minutes: 120,
          priority: "not_urgent_not_important",
          color: "#8B5CF6",
          required: false,
          notes: "게임, 그림, 음악 등 자유롭게",
        },
      ],
    },
    {
      day: "sunday",
      label: "일요일",
      blocks: [
        {
          id: "sun-1",
          title: "모닝 루틴 (가벼운 버전)",
          category: "자기관리",
          start: "08:30",
          end: "09:00",
          duration_minutes: 30,
          priority: "not_urgent_important",
          color: "#F59E0B",
          required: false,
        },
        {
          id: "sun-2",
          title: "집안일 및 정리",
          category: "자기관리",
          start: "10:00",
          end: "11:00",
          duration_minutes: 60,
          priority: "urgent_not_important",
          color: "#F59E0B",
          required: true,
          notes: "청소, 빨래, 장보기",
        },
        {
          id: "sun-3",
          title: "다음 주 준비",
          category: "자기계발",
          start: "16:00",
          end: "16:45",
          duration_minutes: 45,
          priority: "not_urgent_important",
          color: "#6366F1",
          required: true,
          notes: "다음 주 일정 확인 및 루틴 조정",
        },
        {
          id: "sun-4",
          title: "릴렉스 타임",
          category: "휴식",
          start: "20:00",
          end: "21:30",
          duration_minutes: 90,
          priority: "not_urgent_not_important",
          color: "#8B5CF6",
          required: false,
          notes: "영화, 드라마, 음악 감상",
        },
      ],
    },
  ],
};
